name: t_shop
description: "An eCommernce app for sales"

version: 1.0.0+1

environment:
  sdk: ^3.10.7

# ----------------------------- Packages ------------- #
dependencies:
  flutter:
    sdk: flutter
  # Utility Packages
  http: ^1.6.0
  intl: ^0.20.2
  logger: ^2.6.2
  url_launcher: ^6.3.2
  flutter_native_splash: ^2.4.7
  #Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  #State management
  get: ^4.7.3
  get_storage: ^2.1.1
  smooth_page_indicator: ^2.0.1
  lottie: ^3.1.2
  carousel_slider: ^5.1.1
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1

  #firebase
  firebase_core: ^4.4.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/images/brands/
    - assets/images/dashboard/
    - assets/images/forget_password/
    - assets/images/products/
    - assets/images/profile/
    - assets/images/splash_images/
    - assets/images/welcome_images/
    - assets/icons/categories/
    - assets/icons/payment_methods/
  #     - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
